#!/usr/bin/env bash
# Configures Nginx to add a custom X-Served-By header with the server hostname

apt-get update -y
apt-get install nginx -y

sed -i '/listen 80 default_server;/a \ \n\tadd_header X-Served-By $hostname;' /etc/nginx/sites-available/default

service nginx restart